name: raksha_kavach
description: Worker Safety Auditor - Raksha-Kavach
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3

  # Local DB
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

  # UI
  lottie: ^3.1.2
  google_fonts: ^6.2.1

  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
